routes.py
"""This module defines the routes and views for the Flask application."""

from os import environ as env
from urllib.parse import quote_plus, urlencode

from flask import Blueprint, request, jsonify, session, url_for, render_template, redirect, flash
from sqlalchemy import func, desc

from models import NewsItem, User, user_newsitem_likes, user_newsitem_dislikes
from config import db, oauth

ADMIN_PASSWORD = "LinodeServer123" # for Admin Verification

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    """Route for home page, displays paginated news items."""
    # Retrieve the page number from the query parameters, default to 1 if not provided
    page = request.args.get('page', 1, type=int)

    # Define the number of posts per page
    posts_per_page = 10  # You can adjust this based on your preference

    # Subquery to count likes 
    likes_subquery = db.session.query(
        user_newsitem_likes.c.news_item_id,
        func.count('*').label('likes_count')
    ).group_by(user_newsitem_likes.c.news_item_id).subquery()

    # Subquery to count dislikes
    dislikes_subquery = db.session.query(
        user_newsitem_dislikes.c.news_item_id,
        func.count('*').label('dislikes_count')
    ).group_by(user_newsitem_dislikes.c.news_item_id).subquery()

    # Query the paginated posts using SQLAlchemy's paginate method
    posts = NewsItem.query.outerjoin(
        likes_subquery, NewsItem.id == likes_subquery.c.news_item_id
    ).outerjoin(
        dislikes_subquery, NewsItem.id == dislikes_subquery.c.news_item_id
    ).order_by(
        desc(NewsItem.time),  # Sort by time in descending order (most recent first)
        desc(func.coalesce(likes_subquery.c.likes_count, 0) + func.coalesce(dislikes_subquery.c.dislikes_count, 0))  # Sort by total likes and dislikes
    ).paginate(page=page, per_page=posts_per_page, error_out=False)

    return render_template("home.html", session=session.get('user'), posts=posts)


@main.route("/profile")
def profile():
    """Route for users. Initiates login/register if not logged in. Otherwise, opens user profile"""
    # Check if the user is logged in
    if "user" in session:
        # Retrieve the authenticated user from the session
        user_sub = session["user"]["sub"]
        user = User.query.filter_by(sub=user_sub).first()

        return render_template("profile.html", user=user)
    else:
        # Redirect to the login page if the user is not logged in
        return redirect(url_for("main.login"))

@main.route("/login")
def login():
    """Route triggered when user tries to view their profile when not logged in"""
    return oauth.auth0.authorize_redirect(
        redirect_uri=url_for("main.callback", _external=True)
    )

# Update the callback route
@main.route("/callback", methods=["GET", "POST"])
def callback():
    """Route triggered after user logs in/registers. If a new user, they are stored in users db"""
    token = oauth.auth0.authorize_access_token()

    # Ensure that the userinfo URL includes the correct scheme (https://)
    userinfo_url = f'https://{env.get("AUTH0_DOMAIN")}/userinfo'
    
    resp = oauth.auth0.get(userinfo_url)
    
    userinfo = resp.json()
    user_sub = userinfo["sub"]  # Auth0 subject identifier
    
    # Check if the user already exists in your database
    user = User.query.filter_by(sub=user_sub).first()

    if not user:
        # Create a new user in the database
        user = User(
            username=userinfo["nickname"],  # or any other Auth0 user attribute
            email=userinfo["email"],
            sub=user_sub,
            auth0_profile=userinfo,  # Store additional Auth0 profile information if needed
        )
        db.session.add(user)
        db.session.commit()

    session["user"] = userinfo  # Store Auth0 user data in the session
    return redirect("/")

@main.route("/logout")
def logout():
    """Route to log out users. Clears login status and redirects to home"""
    session.clear()
    return redirect(
        "https://" + env.get("AUTH0_DOMAIN")
        + "/v2/logout?"
        + urlencode(
            {
                "returnTo": url_for("main.home", _external=True),
                "client_id": env.get("AUTH0_CLIENT_ID"),
            },
            quote_via=quote_plus,
        )
    )

@main.route('/newsfeeed', methods=['GET'])
def news_feed():
    """Route to diplay newsfeeed as JSON values"""
    # Retrieve the latest 'k' news items from the database
    k = 30
    
    # Subquery to count likes 
    likes_subquery = db.session.query(
        user_newsitem_likes.c.news_item_id,
        func.count('*').label('likes_count')
    ).group_by(user_newsitem_likes.c.news_item_id).subquery()

    # Subquery to count dislikes
    dislikes_subquery = db.session.query(
        user_newsitem_dislikes.c.news_item_id,
        func.count('*').label('dislikes_count')
    ).group_by(user_newsitem_dislikes.c.news_item_id).subquery()

    # Query news items and join with likes and dislikes subqueries to sort
    latest_news_items = db.session.query(
        NewsItem,
        func.coalesce(likes_subquery.c.likes_count, 0).label('total_likes'),
        func.coalesce(dislikes_subquery.c.dislikes_count, 0).label('total_dislikes')
    ).outerjoin(likes_subquery, NewsItem.id == likes_subquery.c.news_item_id) \
    .outerjoin(dislikes_subquery, NewsItem.id == dislikes_subquery.c.news_item_id) \
    .order_by(
        NewsItem.time.desc(),
        (func.coalesce(likes_subquery.c.likes_count, 0) + func.coalesce(dislikes_subquery.c.dislikes_count, 0)).desc()
    ).limit(k).all()

    # Convert the result into a list of dictionaries
    news_items_list = [
        {
            'id': item.NewsItem.id,
            'by': item.NewsItem.by,
            'descendants': item.NewsItem.descendants,
            'kids': item.NewsItem.kids,
            'score': item.NewsItem.score,
            'time': item.NewsItem.time.isoformat(),  # Convert datetime to ISO format
            'title': item.NewsItem.title,
            'type': item.NewsItem.type,
            'url': item.NewsItem.url,
            'total_likes': item.total_likes,  # Aggregate like count
            'total_dislikes': item.total_dislikes,  # Aggregate dislike count
            # Add any more fields you want to include in the JSON response
        } 
        for item in latest_news_items
    ]

    # Respond with the JSON representation of the news items
    return jsonify(news_items_list)

# Add routes for handling likes and dislikes
@main.route("/like/<int:news_item_id>", methods=["POST"])
def like(news_item_id):
    """Route for when logged in users like a post"""
    # Retrieve the authenticated user from the session
    user_sub = session["user"]["sub"]
    user = User.query.filter_by(sub=user_sub).first()

    # Retrieve the news item to be liked
    news_item = NewsItem.query.get(news_item_id)

    # Check if the user has already liked this post
    if user in news_item.likers:
        return jsonify({"message": "You have already liked this post"})

    # Add the user to the likers relationship
    news_item.likers.append(user)
    db.session.commit()

    return jsonify({"message": "Liked successfully"})

@main.route("/dislike/<int:news_item_id>", methods=["POST"])
def dislike(news_item_id):
    """Route for when logged in users dislike a post"""
    # Retrieve the authenticated user from the session
    user_sub = session["user"]["sub"]
    user = User.query.filter_by(sub=user_sub).first()

    # Retrieve the news item to be disliked
    news_item = NewsItem.query.get(news_item_id)

    # Check if the user has already disliked this post
    if user in news_item.dislikers:
        return jsonify({"message": "You have already disliked this post"})

    # Add the user to the dislikers relationship
    news_item.dislikers.append(user)
    db.session.commit()

    return jsonify({"message": "Disliked successfully"})

@main.route('/admin/login', methods=['GET', 'POST'])
def admin_login():
    """Route for users to login as Admins. Password locked."""
    if request.method == 'POST':
        password = request.form['password']
        if password == ADMIN_PASSWORD:
            session['is_admin'] = True
            flash('You have been logged in as admin!', 'success')
            return redirect(url_for('main.admin_dashboard'))
        else:
            flash('Invalid password', 'danger')

    return render_template('admin_login.html')  # You need to create this template

@main.route("/admin")
def admin_dashboard():
    """Route for admins to manage news items. Allows deletion of news items"""
    if not session.get('is_admin'):
        # If the user is not confirmed as admin, redirect to the admin login page
        flash('Please log in to access the admin dashboard.', 'warning')
        return redirect(url_for('main.admin_login'))

    news_items = NewsItem.query.all()
    return render_template("admin.html", posts=news_items)

@main.route("/admin/delete-news-item/<int:news_item_id>", methods=["POST"])
def delete_news_item(news_item_id):
    """Route triggered when admins delete news items. Removes from all relevant db's"""
    if not session.get('is_admin'):
        flash('Unauthorized access. Admins only.', 'danger')
        return redirect(url_for('main.admin_login'))

    news_item = NewsItem.query.get_or_404(news_item_id)
    news_item.likers.clear()
    news_item.dislikers.clear()
    db.session.delete(news_item)
    db.session.commit()

    flash('News item has been deleted', 'success')
    return redirect(url_for('main.admin_dashboard'))

templates/admin.html
<!-- admin.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 20px;
        }
        .news-item {
            border: 1px solid #ddd;
            padding: 10px;
            margin-bottom: 10px;
        }
        form.delete-form {
            display: inline;
        }
    </style>
</head>
<body>
    <h1>Admin Dashboard</h1>
    <form action="{{ url_for('main.logout') }}" method="get">
        <button type="submit">Logout</button>
    </form>
    <hr>
    <div id="news-items">
        <h2>Manage News Items</h2>
        {% for post in posts %}
        <div class="news-item">
            <h3>{{ post.title }}</h3>
            <p>by {{ post.by }} | {{ post.time }}</p>
            <form class="delete-form" action="{{ url_for('main.delete_news_item', news_item_id=post.id) }}" method="post">
                <input type="submit" value="Delete">
            </form>
        </div>
        {% else %}
        <p>No news items found.</p>
        {% endfor %}
    </div>
</body>
</html>

templates/admin_login.html
<!-- admin_login.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
</head>
<body>
    <h1>Admin Login</h1>
    {%- with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
    {%- endwith %}
    <form method="post">
        <input type="password" name="password" placeholder="Enter admin password">
        <input type="submit" value="Login">
    </form>
</body>
</html>

templates/home.html
{% extends "layout.html" %}

{% block content %}
  <h2 class="mt-4">Hacker News</h2>

  {% for post in posts.items %}
    <div class="card mb-2">
      <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.by }} - {{ post.time }}</p>
        
        <!-- Like and Dislike buttons -->
        <div class="btn-group" role="group" aria-label="Like and Dislike buttons">
          <button type="button" class="btn btn-outline-success btn-sm" onclick="likePost({{ post.id }})">Like</button>
          <button type="button" class="btn btn-outline-danger btn-sm" onclick="dislikePost({{ post.id }})">Dislike</button>
        </div>
      </div>
    </div>
  {% endfor %}

  <!-- Pagination -->
  <div class="pagination mt-4">
    <span class="mr-2">Page {{ posts.page }} of {{ posts.pages }}</span>
    
    {% if posts.has_prev %}
      <a class="btn btn-outline-info btn-sm" href="?page={{ posts.prev_num }}">« Prev</a>
    {% endif %}
    
    {% if posts.has_next %}
      <a class="btn btn-outline-info btn-sm" href="?page={{ posts.next_num }}">Next »</a>
    {% endif %}
  </div>

  <!-- JavaScript for handling like and dislike -->
  <script>
    function likePost(newsItemId) {
      fetch(`/like/${newsItemId}`, { method: 'POST' })
        .then(response => response.json())
        .then(data => console.log(data))
        .catch(error => console.error('Error:', error));
    }

    function dislikePost(newsItemId) {
      fetch(`/dislike/${newsItemId}`, { method: 'POST' })
        .then(response => response.json())
        .then(data => console.log(data))
        .catch(error => console.error('Error:', error));
    }
  </script>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Directory</h3>
              <ul class="list-group">
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('main.home') }}">Home</a></li>
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('main.news_feed') }}">Newsfeeed</a></li>
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('main.profile') }}">Profile</a></li>
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('main.logout') }}">Logout</a></li> 
                <li class="list-group-item list-group-item-light"><a href="{{ url_for('main.admin_dashboard') }}">Admin</a></li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/newsfeed.html
{% extends "layout.html" %}

{% block content %}
<div>
    <h1>Hacker News Feed </h1>
    <ul id="news-list">
        {% for news in newsfeed %}
        <li>
            <h2>{{ news.title }}</h2>
            <p>{{ news.description }}</p>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/profile.html
{% extends "layout.html" %}

{% block content %}
  <h2 class="mt-4">User Profile</h2>
  
  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title">User Information</h5>
      <p class="card-text"><strong>Username:</strong> {{ user.username }}</p>
      <p class="card-text"><strong>Email:</strong> {{ user.email }}</p>
      <p class="card-text"><strong>Auth0 Sub:</strong> {{ user.sub }}</p>
      <p class="card-text"><strong>Auth0 Profile:</strong> {{ user.auth0_profile }}</p>
    </div>
  </div>

  <h5 class="mt-4">Liked News Items</h5>
  {% if user.liked_news_items %}
    <ul>
      {% for news_item in user.liked_news_items %}
        <li>{{ news_item.title }} - {{ news_item.by }} - {{ news_item.time }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No liked news items.</p>
  {% endif %}

  <h5 class="mt-4">Disliked News Items</h5>
  {% if user.disliked_news_items %}
    <ul>
      {% for news_item in user.disliked_news_items %}
        <li>{{ news_item.title }} - {{ news_item.by }} - {{ news_item.time }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No disliked news items.</p>
  {% endif %}
{% endblock %}